kind: pipeline
name: docker

platform:
  runner: 10.11.92.36

volumes:
  - name: golang
    host:
      path: /data/cache/golang/pkg
  - name: docker
    host:
      path: /var/run/docker.sock

workspace:
  base: /go
  path: src/github.com/docker/libnetwork

steps:
  - name: golang
    image: registry.cn-qingdao.aliyuncs.com/wod/golang:1.17.3-bullseye
    volumes:
      - name: golang
        path: /go/pkg
    environment:
      GO111MODULE: off
    commands:
      - bash .beagle/build.sh

  - name: docker-amd64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/dockerfile
      cwd: dist
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.14-amd64
      repo: wod/docker-proxy
      version: 19.03
      channel: amd64
      args: 'TARGETOS=linux,TARGETARCH=amd64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang

  - name: docker-arm64
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/dockerfile
      cwd: dist
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.14-arm64
      repo: wod/docker-proxy
      version: 19.03
      channel: arm64
      args: 'TARGETOS=linux,TARGETARCH=arm64'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang

  - name: docker-ppc64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/dockerfile
      cwd: dist
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.14-ppc64le
      repo: wod/docker-proxy
      version: 19.03
      channel: ppc64le
      args: 'TARGETOS=linux,TARGETARCH=ppc64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang

  - name: docker-mips64le
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker:1.0
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      dockerfile: .beagle/dockerfile
      cwd: dist
      base: registry.cn-qingdao.aliyuncs.com/wod/alpine:3.11-mips64le
      repo: wod/docker-proxy
      version: 19.03
      channel: mips64le
      args: 'TARGETOS=linux,TARGETARCH=mips64le'
      registry: registry.cn-qingdao.aliyuncs.com
      registry_user:
        from_secret: REGISTRY_USER_ALIYUN
      registry_password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - golang

  - name: docker-arch
    image: registry.cn-qingdao.aliyuncs.com/wod/devops-docker-manifest:v1.2.3
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/mips64le
      template: registry.cn-qingdao.aliyuncs.com/wod/docker-proxy:19.03-ARCH
      target: registry.cn-qingdao.aliyuncs.com/wod/docker-proxy:19.03
      username:
        from_secret: REGISTRY_USER_ALIYUN
      password:
        from_secret: REGISTRY_PASSWORD_ALIYUN
    depends_on:
      - docker-amd64
      - docker-arm64
      - docker-ppc64le
      - docker-mips64le

---
kind: secret
name: REGISTRY_USER_ALIYUN
get:
  path: devops-registry-aliyun
  name: USERNAME

---
kind: secret
name: REGISTRY_PASSWORD_ALIYUN
get:
  path: devops-registry-aliyun
  name: PASSWORD
